FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

ARG ARM_DL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2?revision=ca0cbf9c-9de2-491c-ac48-898b5bbc0443&la=en&hash=68760A8AE66026BCF99F05AC017A6A50C6FD832A

RUN apt update && apt install -y git gettext wget python3 python3-pip && pip3 install huffman && \
    mkdir -p /arm

RUN wget ${ARM_DL} -O /arm/arm.bz2 && \
    cd /arm && \
    tar xvf /arm/arm.bz2

ENV PATH="/arm/gcc-arm-none-eabi-10-2020-q4-major/bin:$PATH"

WORKDIR /work

ADD . /work

RUN cd /work && make -C mpy-cross

RUN cd /work/ports/atmel-samd && \
    make BOARD=matrixportal_m4 -j4

